Shameless self promo
pwicherski/TestowanieOprogramowania pull request #18
Opened 2018-09-05 11:10 UTC by mwyrodek

Dodałem link do mojego bloga proszę ładnie o publish :)

2018-09-06 19:09 UTC, pwicherski requested changes

2018-09-06 19:09 UTC, pwicherski commented on gdzie-szukac-wiedzy/polskie-blogi.md
> +* [https://thebrokentest.com](https://thebrokentest.com/?utm_source=PWGit)
Bez UTMa i będzie approve :)

2018-09-06 19:18 UTC, mwyrodek commented on gdzie-szukac-wiedzy/polskie-blogi.md
> +* [https://thebrokentest.com](https://thebrokentest.com/?utm_source=PWGit)
done

2018-09-08 16:21 UTC, pwicherski approved these changes

2018-09-08 16:21 UTC, merged