Bootcampy
pwicherski/TestowanieOprogramowania pull request #33
Opened 2019-05-17 18:07 UTC by artekzet

Cześć, ostatnio na grupie było parę pytań o bootcampy, miałem wolne pół godziny więc doklejam te firmy + kilka dyskusji.

2019-05-18 14:07 UTC, pwicherski requested changes

2019-05-18 14:07 UTC, pwicherski commented on SUMMARY.md
> +* [Bootcampy, czyli szkolenia długoterminowe](studia-z-testowania.md)
10 dni to nie bootcamp. Do tego wydzielanie kursów i bootcampówna dwie różne strony jest bezzasadne.
Zarówno kursy jak i bootcampy moga być na jednej stronie, przykładowo oddzielone.
Skróć nazwę na same "Kursy fizyczne" i popraw nazwę pliku "studia-z-testowania.md" aby była odpowiednia dla tytułu strony.

2019-05-18 14:07 UTC, pwicherski commented on bootcampy-szkolenia-dlugoterminowe.md
> +### Firmy szkoleniowe
Zamień na:
### Szkolenia krótkoterminowe

### Szkolenia długoterminowe

I rozdziel te szklenia, które uznajesz za długoterminowe i krótkoterminowe w odpowiednie miejsca.

2019-05-18 14:07 UTC, pwicherski commented on bootcampy-szkolenia-dlugoterminowe.md
> +Zanim zdecydujesz się poświęcić swój czas i pieniądze, poczytaj
Przyda się link do wszystkich dyskusji z tej kategorii:
https://www.facebook.com/groups/141683635854223/post_tags/?post_tag_id=1765193666836537

2019-05-18 14:07 UTC, pwicherski commented on bootcampy-szkolenia-dlugoterminowe.md
> +* [Dyskusja 1](https://www.facebook.com/groups/TestowanieOprogramowania/permalink/1819919381363965/)
Listę powiązanych dyskusji możnaby zrobić troszkę czytelniej przy rozdzieleniu na szkolenia i szkolenia długoterminowe.

* Lista przykładowych dyskusji na temat długoterminowych szkoleń z testowania
  * [Dyskusja 1](https://www.facebook.com/groups/TestowanieOprogramowania/permalink/1819919381363965/)
  * [Dyskusja 2](https://www.facebook.com/groups/TestowanieOprogramowania/permalink/2007149499307618/)
  * [Dyskusja 3](https://www.facebook.com/groups/TestowanieOprogramowania/permalink/2018886294800605/)

2019-05-18 14:07 UTC, pwicherski commented on bootcampy-szkolenia-dlugoterminowe.md
> +* [Software Development Academy](https://sdacademy.pl/)
Podaj linki do konkretnej oferty szkolenia lub bootcampu danej firmy. Nie link do samej firmy.

2019-05-18 14:07 UTC, pwicherski commented
Hiho! :)

Dzięki za wkład!

2019-05-20 15:29 UTC, artekzet commented on SUMMARY.md
> +* [Bootcampy, czyli szkolenia długoterminowe](studia-z-testowania.md)
Done

2019-05-20 15:29 UTC, artekzet commented on bootcampy-szkolenia-dlugoterminowe.md
> +### Firmy szkoleniowe
Done

2019-05-20 15:32 UTC, artekzet commented on bootcampy-szkolenia-dlugoterminowe.md
> +Zanim zdecydujesz się poświęcić swój czas i pieniądze, poczytaj
Done

2019-05-20 15:32 UTC, artekzet commented on bootcampy-szkolenia-dlugoterminowe.md
> +* [Dyskusja 1](https://www.facebook.com/groups/TestowanieOprogramowania/permalink/1819919381363965/)
Masz coś konkretnego na myśli? Ciężko te dyskusje jednoznacznie przypisać do konkretnej firmy :)

2019-05-20 15:34 UTC, artekzet commented on bootcampy-szkolenia-dlugoterminowe.md
> +* [Software Development Academy](https://sdacademy.pl/)
Starałem się tak robić, ale w przypadku SDA nie ma odnośnika do ogólnego kursu testerskiego, jest tylko do konkretnych edycji.

2019-05-21 15:41 UTC, artekzet commented
Poprawki wdrożone ;)

2019-05-22 00:23 UTC, pwicherski commented on bootcampy-szkolenia-dlugoterminowe.md
> +* [Dyskusja 1](https://www.facebook.com/groups/TestowanieOprogramowania/permalink/1819919381363965/)
Nie tyle do konkretnej firmy co do kursów krótkoterminowych i długoterminowych :)

2019-05-22 00:23 UTC, pwicherski commented on bootcampy-szkolenia-dlugoterminowe.md
> +* [Software Development Academy](https://sdacademy.pl/)
Fair enough :)

2019-05-22 00:24 UTC, pwicherski requested changes
https://github.com/pwicherski/TestowanieOprogramowania/pull/33#discussion_r286272627

2019-05-22 16:26 UTC, pwicherski approved these changes

2019-05-22 16:26 UTC, pwicherski commented
Resztę zmian wprowadzę sam, dzięki bardzo :) 👍

2019-05-22 17:04 UTC, pwicherski approved these changes

2019-05-22 17:05 UTC, merged